language: php
php: [ 7.4 ]
sudo: false

install:
  - travis_retry composer install --no-interaction --prefer-dist --optimize-autoloader

script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit

after_success:
  - cd build/output
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
